---
- name: 主机基本设置
  hosts: all
  gather_facts: "{{ set_gather_facts | default(True) }}"
  user: root
  pre_tasks:
     - name: 检查支持的操作系统
       assert:
         that:
           - (ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7')
         msg: "仅支持(redhat) CentOS 7 (WIP)"


  roles:
    - role: "init_hosts"
      tags:
        - init

